[application]

[web.app]

# HTML title tag content
title = "Locked In"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/styles/main.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "richard"
publisher = "richard"
icon = ["assets/favicon.ico"]

[bundle.windows]
icon_path = "assets/favicon.ico"
